export const destinations = [
  {
    id: 1,
    title: "Manali",
    tagline: "Valley of Gods",
    gradient: "from-green-500 to-emerald-600",
    price: "₹12,999",
    duration: "5 Days / 4 Nights",
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1609920658906-8223bd289001?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWFuYWxpfGVufDB8fDB8fHww",
    highlights: ["Snow Mountains", "Adventure Sports", "Valley Views"],
    discount: "25% OFF",
    packages: 12,
    description: "Experience the breathtaking beauty of Himalayan mountains with snow-capped peaks, adventure sports, and serene valley views.",
    bestTime: "March to June",
    activities: ["Trekking", "Skiing", "Paragliding", "River Rafting"]
  },
  {
    id: 2,
    title: "Goa",
    tagline: "Beach Paradise",
    gradient: "from-blue-500 to-cyan-600",
    price: "₹15,999",
    duration: "4 Days / 3 Nights",
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z29hfGVufDB8fDB8fHww",
    highlights: ["Beaches", "Nightlife", "Water Sports"],
    discount: "30% OFF",
    packages: 18,
    description: "Relax on pristine golden beaches, enjoy vibrant nightlife, and experience thrilling water sports in this coastal paradise.",
    bestTime: "November to February",
    activities: ["Beach Hopping", "Water Sports", "Nightlife", "Seafood"]
  },
  {
    id: 3,
    title: "Kerala",
    tagline: "God's Own Country",
    gradient: "from-purple-500 to-pink-600",
    price: "₹18,999",
    duration: "6 Days / 5 Nights",
    rating: "4.7",
    image: "https://images.unsplash.com/photo-1593872356907-d67e8587d0f9?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGtlcmFsYXxlbnwwfHwwfHx8MA%3D%3D",
    highlights: ["Backwaters", "Houseboats", "Ayurveda"],
    discount: "27% OFF",
    packages: 15,
    description: "Cruise through serene backwaters, stay in traditional houseboats, and rejuvenate with authentic Ayurvedic treatments.",
    bestTime: "September to March",
    activities: ["Backwater Cruise", "Houseboat Stay", "Ayurvedic Massage", "Kathakali Show"]
  },
  {
    id: 4,
    title: "Dubai",
    tagline: "City of Gold",
    gradient: "from-amber-500 to-orange-600",
    price: "₹45,999",
    duration: "5 Days / 4 Nights",
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZHViYWl8ZW58MHx8MHx8fDA%3D",
    highlights: ["Burj Khalifa", "Desert Safari", "Shopping"],
    discount: "30% OFF",
    packages: 25,
    description: "Experience luxury in the desert city with world-class shopping, iconic architecture, and thrilling desert adventures.",
    bestTime: "November to March",
    activities: ["Burj Khalifa", "Desert Safari", "Dubai Mall", "Dhow Cruise"]
  },
  {
    id: 5,
    title: "Singapore",
    tagline: "Lion City",
    gradient: "from-red-500 to-pink-600",
    price: "₹38,999",
    duration: "4 Days / 3 Nights",
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2luZ2Fwb3JlfGVufDB8fDB8fHww",
    highlights: ["Gardens by the Bay", "Universal Studios", "Marina Bay"],
    discount: "26% OFF",
    packages: 14,
    description: "Explore futuristic gardens, enjoy world-class theme parks, and experience the perfect blend of cultures in this modern city-state.",
    bestTime: "February to April",
    activities: ["Gardens by the Bay", "Universal Studios", "Sentosa Island", "Night Safari"]
  },
  {
    id: 6,
    title: "Bali",
    tagline: "Island of Gods",
    gradient: "from-teal-500 to-green-600",
    price: "₹42,999",
    duration: "6 Days / 5 Nights",
    rating: "4.9",
    image: "https://plus.unsplash.com/premium_photo-1677829177642-30def98b0963?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmFsaXxlbnwwfHwwfHx8MA%3D%3D",
    highlights: ["Beaches", "Temples", "Rice Terraces"],
    discount: "27% OFF",
    packages: 16,
    description: "Discover tropical paradise with stunning beaches, ancient temples, and lush rice terraces in this Indonesian gem.",
    bestTime: "April to October",
    activities: ["Beach Clubs", "Temple Tours", "Rice Terrace Trek", "Traditional Dance"]
  },
  {
    id: 7,
    title: "Maldives",
    tagline: "Tropical Paradise",
    gradient: "from-cyan-500 to-blue-600",
    price: "₹55,999",
    duration: "5 Days / 4 Nights",
    rating: "4.9",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1000&auto=format&fit=crop&q=60",
    highlights: ["Overwater Villas", "Crystal Clear Water", "Private Beaches"],
    discount: "28% OFF",
    packages: 10,
    description: "Experience luxury in overwater villas surrounded by crystal-clear turquoise waters and pristine white sand beaches.",
    bestTime: "November to April",
    activities: ["Snorkeling", "Scuba Diving", "Island Hopping", "Sunset Cruise"]
  },
  {
    id: 8,
    title: "Rajasthan",
    tagline: "Land of Royals",
    gradient: "from-yellow-500 to-orange-600",
    price: "₹22,999",
    duration: "6 Days / 5 Nights",
    rating: "4.8",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1000&auto=format&fit=crop&q=60",
    highlights: ["Royal Palaces", "Desert Safari", "Heritage Hotels"],
    discount: "24% OFF",
    packages: 20,
    description: "Explore majestic forts, royal palaces, desert landscapes, and experience the rich cultural heritage of Rajasthan.",
    bestTime: "October to March",
    activities: ["Camel Safari", "Palace Tour", "Cultural Show", "Desert Camping"]
  }
]