// ============================================================
//  experienc.js  —  Experience Categories Model
//  Fully derived from packages.js data (50 cities, 12 types)
//  Each category maps to real packages via tourism_type / category[]
// ============================================================

export const categories = [
  {
    id: "international",
    name: "International",
    icon: "✈️",
    gradient: "from-[#0f6477] to-[#1a8fa6]",
    accentColor: "#0f6477",
    lightBg: "rgba(15,100,119,0.08)",
    border: "rgba(15,100,119,0.25)",
    description: "48 world-class destinations across 6 continents, curated for every traveller.",
    packageCount: 48,
    topDestinations: ["Paris", "Dubai", "Tokyo", "Bali", "New York", "Singapore"],
    features: [
      "Visa assistance & guidance",
      "International flight booking",
      "Hotel & resort stays",
      "Expert local guides",
      "Travel insurance",
      "24/7 trip support",
    ],
    tourismTypes: ["Cultural", "Heritage", "Beach", "Adventure", "Luxury", "Urban"],
    bestTime: "Year-round",
    badge: "Most Popular",
  },
  {
    id: "domestic",
    name: "Domestic",
    icon: "🇮🇳",
    gradient: "from-orange-500 to-amber-500",
    accentColor: "#f97316",
    lightBg: "rgba(249,115,22,0.08)",
    border: "rgba(249,115,22,0.25)",
    description: "India's finest — the Taj Mahal, Mughal forts, and heritage trails, all close to home.",
    packageCount: 2,
    topDestinations: ["Delhi", "Agra & Taj Mahal"],
    features: [
      "No passport required",
      "Train & cab transfers",
      "Heritage guided tours",
      "Authentic local cuisine",
      "Flexible travel dates",
      "Budget-friendly options",
    ],
    tourismTypes: ["Heritage", "Cultural", "Religious"],
    bestTime: "Oct – Mar",
    badge: "India Special",
  },
  {
    id: "family",
    name: "Family",
    icon: "👨‍👩‍👧‍👦",
    gradient: "from-violet-500 to-purple-600",
    accentColor: "#7c3aed",
    lightBg: "rgba(124,58,237,0.08)",
    border: "rgba(124,58,237,0.25)",
    description: "Safe, fun, and unforgettable — from Disney Orlando to Singapore's Gardens by the Bay.",
    packageCount: 18,
    topDestinations: ["Orlando", "Singapore", "Bali", "London", "Sydney"],
    features: [
      "Kid-friendly itineraries",
      "Theme park access",
      "Family room bookings",
      "Child safety protocols",
      "Age-appropriate activities",
      "Group discounts",
    ],
    tourismTypes: ["Theme Parks", "Beach", "Urban", "Wildlife", "Nature"],
    bestTime: "School holidays",
    badge: "Family Friendly",
  },
  {
    id: "religion",
    name: "Religious",
    icon: "🙏",
    gradient: "from-amber-500 to-yellow-500",
    accentColor: "#d97706",
    lightBg: "rgba(217,119,6,0.08)",
    border: "rgba(217,119,6,0.25)",
    description: "Sacred journeys to the world's holiest sites — Jerusalem, Istanbul, Kathmandu & Agra.",
    packageCount: 5,
    topDestinations: ["Jerusalem", "Istanbul", "Kathmandu", "Agra", "Rome"],
    features: [
      "Pilgrimage-focused itineraries",
      "Temple & shrine access",
      "Spiritual guides",
      "Prayer & meditation time",
      "Religious ceremony visits",
      "Multi-faith coverage",
    ],
    tourismTypes: ["Religious", "Heritage", "Cultural", "Historical"],
    bestTime: "Oct – Mar",
    badge: "Spiritual",
  },
  {
    id: "cultural",
    name: "Cultural",
    icon: "🎭",
    gradient: "from-rose-500 to-pink-600",
    accentColor: "#e11d48",
    lightBg: "rgba(225,29,72,0.08)",
    border: "rgba(225,29,72,0.25)",
    description: "Art, history, food, and traditions — 15+ cultural hotspots from Paris to Mexico City.",
    packageCount: 15,
    topDestinations: ["Paris", "Rome", "Barcelona", "Istanbul", "Tokyo", "Mexico City"],
    features: [
      "Museum skip-the-line passes",
      "Local cooking classes",
      "Cultural walking tours",
      "Art gallery visits",
      "Traditional performances",
      "Local food trails",
    ],
    tourismTypes: ["Cultural", "Heritage", "Historical", "Modern Culture"],
    bestTime: "Apr – Oct",
    badge: "Culture Rich",
  },
  {
    id: "adventure",
    name: "Adventure",
    icon: "🏔️",
    gradient: "from-emerald-500 to-teal-600",
    accentColor: "#059669",
    lightBg: "rgba(5,150,105,0.08)",
    border: "rgba(5,150,105,0.25)",
    description: "Bungee in Queenstown, trek Machu Picchu, swim Devil's Pool, fly over Everest.",
    packageCount: 8,
    topDestinations: ["Queenstown", "Cusco", "Victoria Falls", "Kathmandu", "Vancouver"],
    features: [
      "Certified adventure guides",
      "Safety gear included",
      "Bungee & skydiving",
      "Trek & mountain hikes",
      "White-water rafting",
      "Wildlife safaris",
    ],
    tourismTypes: ["Adventure", "Nature", "Wildlife"],
    bestTime: "May – Oct",
    badge: "Adrenaline",
  },
  {
    id: "beach",
    name: "Beach & Island",
    icon: "🏖️",
    gradient: "from-cyan-500 to-sky-500",
    accentColor: "#0891b2",
    lightBg: "rgba(8,145,178,0.08)",
    border: "rgba(8,145,178,0.25)",
    description: "Bali's sacred shores, Cancun's Caribbean turquoise, Miami's Art Deco, Sydney's Bondi.",
    packageCount: 6,
    topDestinations: ["Bali", "Cancun", "Miami", "Barcelona", "Sydney", "Rio de Janeiro"],
    features: [
      "Beach resort stays",
      "Snorkelling & diving",
      "Water sports access",
      "Sunset cruise",
      "Beachside dining",
      "Island hopping",
    ],
    tourismTypes: ["Beach", "Romantic", "Adventure", "Urban"],
    bestTime: "Apr – Oct",
    badge: "Sun & Sand",
  },
  {
    id: "luxury",
    name: "Luxury",
    icon: "💎",
    gradient: "from-slate-700 to-slate-900",
    accentColor: "#334155",
    lightBg: "rgba(51,65,85,0.08)",
    border: "rgba(51,65,85,0.25)",
    description: "5-star resorts, private guides, Michelin dining — Dubai, Zurich, Singapore & Paris.",
    packageCount: 4,
    topDestinations: ["Dubai", "Zurich", "Singapore", "Paris"],
    features: [
      "5-star hotel stays",
      "Private airport transfers",
      "Michelin restaurant dining",
      "Exclusive lounge access",
      "Personal travel concierge",
      "Luxury yacht / helicopter",
    ],
    tourismTypes: ["Luxury", "Shopping", "Urban"],
    bestTime: "Year-round",
    badge: "Premium",
  },
  {
    id: "wildlife",
    name: "Wildlife & Safari",
    icon: "🦁",
    gradient: "from-yellow-500 to-orange-500",
    accentColor: "#ca8a04",
    lightBg: "rgba(202,138,4,0.08)",
    border: "rgba(202,138,4,0.25)",
    description: "Big Five game drives, Masai Mara balloon safaris, penguin colonies & whale watching.",
    packageCount: 3,
    topDestinations: ["Nairobi", "Cape Town", "Victoria Falls"],
    features: [
      "Big Five game drives",
      "Expert wildlife rangers",
      "Hot air balloon safari",
      "Bush camp stays",
      "Bird watching tours",
      "Maasai cultural village",
    ],
    tourismTypes: ["Wildlife", "Nature", "Adventure"],
    bestTime: "Jul – Oct",
    badge: "Big Five",
  },
  {
    id: "romantic",
    name: "Romantic",
    icon: "💕",
    gradient: "from-pink-500 to-rose-500",
    accentColor: "#db2777",
    lightBg: "rgba(219,39,119,0.08)",
    border: "rgba(219,39,119,0.25)",
    description: "Paris sunsets, Venice gondolas, Bali spa retreats — perfect for couples & honeymoons.",
    packageCount: 5,
    topDestinations: ["Paris", "Venice", "Bali", "Rio de Janeiro", "Barcelona"],
    features: [
      "Couple-exclusive packages",
      "Romantic candlelight dining",
      "Honeymoon room setup",
      "Spa & wellness retreats",
      "Sunset cruises",
      "Private photography",
    ],
    tourismTypes: ["Romantic", "Beach", "Cultural"],
    bestTime: "Apr – Jun, Sep – Nov",
    badge: "Honeymoon",
  },
  {
    id: "historical",
    name: "Historical",
    icon: "🏛️",
    gradient: "from-stone-500 to-stone-700",
    accentColor: "#78716c",
    lightBg: "rgba(120,113,108,0.08)",
    border: "rgba(120,113,108,0.25)",
    description: "Walk the Great Wall, explore Pompeii, discover Machu Picchu — history at every step.",
    packageCount: 7,
    topDestinations: ["Cairo", "Athens", "Rome", "Beijing", "Cusco", "Agra"],
    features: [
      "Archaeologist-led tours",
      "UNESCO World Heritage sites",
      "Ancient ruins access",
      "Museum guided tours",
      "Skip-the-line tickets",
      "Historical documentaries",
    ],
    tourismTypes: ["Historical", "Heritage", "Cultural"],
    bestTime: "Oct – Apr",
    badge: "Ancient Wonders",
  },
  {
    id: "urban",
    name: "City & Urban",
    icon: "🏙️",
    gradient: "from-indigo-500 to-blue-600",
    accentColor: "#4f46e5",
    lightBg: "rgba(79,70,229,0.08)",
    border: "rgba(79,70,229,0.25)",
    description: "NYC's electric skyline, Tokyo's neon streets, Dubai's supertalls — city life at its peak.",
    packageCount: 12,
    topDestinations: ["New York City", "Tokyo", "Dubai", "Singapore", "London", "Hong Kong"],
    features: [
      "City pass inclusions",
      "Rooftop bar access",
      "Metro & transit cards",
      "Shopping district tours",
      "Nightlife experiences",
      "Street food walks",
    ],
    tourismTypes: ["Urban", "Business", "Shopping", "Modern Culture"],
    bestTime: "Year-round",
    badge: "Cosmopolitan",
  },
];