// ============================================================
//  featureModel.js
//  Derived from packages.js  —  each card = a travel region
//  Shows: continent, destination count, top picks, best time,
//         tourism types, and a highlight stat.
//  Used by: InfiniteSlider (destination showcase carousel)
// ============================================================

export const features = [
  {
    id: "europe",
    color: "blue",
    icon: "🗼",
    region: "Europe",
    stat: "10 Destinations",
    tagline: "Romance, Heritage & Alpine Magic",
    description:
      "From Paris's golden Eiffel glow to Prague's fairy-tale spires — Europe offers the world's finest art, history, and cuisine in one continent.",
    topPicks: ["Paris", "Rome", "Barcelona", "Venice", "Zurich"],
    bestTime: "Apr – Oct",
    tourismTypes: ["Cultural", "Heritage", "Romantic", "Nature"],
    highlight: "4.8★ Avg Rating",
  },
  {
    id: "middle-east",
    color: "orange",
    icon: "🕌",
    region: "Middle East",
    stat: "3 Destinations",
    tagline: "Minarets, Luxury & Sacred Lands",
    description:
      "Dubai's record-breaking skyline, Istanbul's Blue Mosque echoing across two continents, and Jerusalem's deeply moving Old City — the Middle East is unforgettable.",
    topPicks: ["Dubai", "Istanbul", "Jerusalem"],
    bestTime: "Nov – Apr",
    tourismTypes: ["Luxury", "Cultural", "Religious"],
    highlight: "4.8★ Avg Rating",
  },
  {
    id: "asia",
    color: "green",
    icon: "⛩️",
    region: "Asia",
    stat: "10 Destinations",
    tagline: "Ancient Temples, Neon Cities & Island Bliss",
    description:
      "Tokyo's neon future beside ancient shrines, Bali's emerald rice terraces, and Singapore's futuristic supertrees — Asia is endlessly diverse and exciting.",
    topPicks: ["Tokyo", "Bali", "Singapore", "Bangkok", "Seoul"],
    bestTime: "Oct – Apr",
    tourismTypes: ["Modern Culture", "Beach", "Heritage", "Wildlife"],
    highlight: "4.7★ Avg Rating",
  },
  {
    id: "americas",
    color: "purple",
    icon: "🗽",
    region: "Americas",
    stat: "15 Destinations",
    tagline: "Wild Nature, Theme Parks & Carnival Nights",
    description:
      "Machu Picchu emerging from morning clouds, Manhattan's electric skyline, Orlando's magical theme parks, and Rio's samba-infused Carnival — the Americas have it all.",
    topPicks: ["Cusco & Machu Picchu", "New York City", "Orlando", "Rio de Janeiro", "Cancun"],
    bestTime: "Year-round (varies)",
    tourismTypes: ["Heritage", "Urban", "Adventure", "Beach", "Theme Parks"],
    highlight: "4.7★ Avg Rating",
  },
  {
    id: "africa",
    color: "cyan",
    icon: "🦁",
    region: "Africa",
    stat: "5 Destinations",
    tagline: "Big Five Safari, Pyramids & Waterfall Thunder",
    description:
      "Track lions at dawn in the Masai Mara, stand before the last wonder of the ancient world in Cairo, and feel the spray of Victoria Falls — Africa changes you.",
    topPicks: ["Nairobi Safari", "Cape Town", "Cairo", "Victoria Falls", "Marrakesh"],
    bestTime: "Jul – Oct",
    tourismTypes: ["Wildlife", "Historical", "Nature", "Cultural"],
    highlight: "4.7★ Avg Rating",
  },
  {
    id: "australia-pacific",
    color: "indigo",
    icon: "🦘",
    region: "Australia & Pacific",
    stat: "5 Destinations",
    tagline: "Opera House, Bungee & Barrier Reef",
    description:
      "Sydney's iconic harbour, Queenstown's adrenaline playgrounds, Melbourne's laneway coffee culture, and the Great Barrier Reef — the Pacific is big, bold, and breathtaking.",
    topPicks: ["Sydney", "Queenstown", "Melbourne", "Auckland", "Brisbane"],
    bestTime: "Sep – May",
    tourismTypes: ["Adventure", "Beach", "Urban", "Nature"],
    highlight: "4.7★ Avg Rating",
  },
  {
    id: "india",
    color: "orange",
    icon: "🕍",
    region: "India — Domestic",
    stat: "2 Destinations",
    tagline: "Golden Triangle & Mughal Grandeur",
    description:
      "The Taj Mahal at sunrise — one building that leaves twenty million visitors speechless every year — and Delhi's seven-layered history sprawling before you.",
    topPicks: ["Agra & Taj Mahal", "Delhi"],
    bestTime: "Oct – Mar",
    tourismTypes: ["Heritage", "Cultural", "Religious"],
    highlight: "4.8★ Avg Rating",
  },
  {
    id: "popular",
    color: "green",
    icon: "🔥",
    region: "Most Popular",
    stat: "10 Top Picks",
    tagline: "Our Best-Loved Packages",
    description:
      "Handpicked by thousands of happy travellers — Paris, Dubai, Tokyo, Bali, Nairobi Safari, Orlando, Singapore, Cusco, Barcelona & London top our charts every season.",
    topPicks: ["Paris", "Dubai", "Tokyo", "Bali", "Nairobi Safari", "Orlando", "Singapore", "Cusco", "Barcelona", "London"],
    bestTime: "Varies by destination",
    tourismTypes: ["All Types"],
    highlight: "4.8★ Avg Rating",
  },
  {
    id: "family",
    color: "blue",
    icon: "👨‍👩‍👧‍👦",
    region: "Family Packages",
    stat: "18 Packages",
    tagline: "Memories the Whole Family Will Love",
    description:
      "From Orlando's Disney magic to Singapore's Universal Studios, Bali's temple ceremonies, and Sydney's wildlife encounters — every family finds its perfect match here.",
    topPicks: ["Orlando", "Singapore", "Bali", "Sydney", "London"],
    bestTime: "School holidays",
    tourismTypes: ["Theme Parks", "Beach", "Urban", "Wildlife"],
    highlight: "Family Friendly",
  },
  {
    id: "adventure",
    color: "cyan",
    icon: "🏔️",
    region: "Adventure",
    stat: "8 Packages",
    tagline: "Bungee, Trek & Safari",
    description:
      "Queenstown's AJ Hackett bungee, Cusco's Rainbow Mountain trek, Victoria Falls' Devil's Pool, and Kathmandu's Himalayan flights — for those who travel for the thrill.",
    topPicks: ["Queenstown", "Cusco", "Victoria Falls", "Kathmandu", "Vancouver"],
    bestTime: "May – Oct",
    tourismTypes: ["Adventure", "Nature", "Wildlife"],
    highlight: "Adrenaline Rated",
  },
  {
    id: "beach",
    color: "purple",
    icon: "🏖️",
    region: "Beach & Island",
    stat: "6 Packages",
    tagline: "Turquoise Water & White Sand",
    description:
      "Bali's sacred shores, Cancun's Caribbean blues, Miami's Art Deco sunsets, and Barcelona's Barceloneta beach — sun, sand, and sea at its finest.",
    topPicks: ["Bali", "Cancun", "Miami", "Barcelona", "Sydney"],
    bestTime: "Apr – Oct",
    tourismTypes: ["Beach", "Romantic", "Cultural"],
    highlight: "Beach Certified",
  },
  {
    id: "religious",
    color: "indigo",
    icon: "🙏",
    region: "Religious & Spiritual",
    stat: "5 Packages",
    tagline: "Sacred Journeys Across Faiths",
    description:
      "Jerusalem's Western Wall and Holy Sepulchre, Istanbul's Blue Mosque, Kathmandu's Pashupatinath aarti, and Agra's Fatehpur Sikri — journeys that touch the soul.",
    topPicks: ["Jerusalem", "Istanbul", "Kathmandu", "Agra", "Rome"],
    bestTime: "Oct – Mar",
    tourismTypes: ["Religious", "Heritage", "Cultural"],
    highlight: "Multi-Faith",
  },
];