 // Static packages data instead of import
  export const packages = [
    {
      id: 1,
      title: "Manali Adventure Package",
      location: "Manali",
      duration: "5 Days / 4 Nights",
      image:"/assets/bg.jpg",
      price: "₹12,999",
      originalPrice: "₹18,999",
      rating: 4.8,
      category: "Adventure",
      inclusions: ["Hotel Stay", "Meals", "Sightseeing", "Adventure Activities"],
      discount: 32,
      description: "Experience the thrill of Himalayan adventure with snow-capped mountains, adventure sports, and breathtaking valley views.",
      popular: true
    },
    {
      id: 2,
      title: "Goa Beach Paradise",
      location: "Goa",
      duration: "4 Days / 3 Nights",
      price: "₹15,999",
      originalPrice: "₹22,999",
      image:"/assets/kd.jpg",
      rating: 4.9,
      category: "Beach",
      inclusions: ["Resort Stay", "Breakfast", "Water Sports", "Nightlife"],
      discount: 30,
      description: "Relax on pristine beaches, enjoy water sports, and experience vibrant nightlife in this beach paradise.",
      popular: true
    },
    {
      id: 3,
      title: "Kerala Backwaters",
      location: "Kerala",
      duration: "6 Days / 5 Nights",
      price: "₹18,999",
      originalPrice: "₹25,999",
      image:"/assets/mt1.jpg",
      rating: 4.7,
      category: "Cultural",
      inclusions: ["Houseboat Stay", "All Meals", "Cultural Programs", "Ayurvedic Massage"],
      discount: 27,
      description: "Cruise through serene backwaters, experience traditional culture, and rejuvenate with authentic Ayurvedic treatments.",
      popular: true
    },
    {
      id: 4,
      title: "Dubai City Experience",
      location: "Dubai",
      duration: "5 Days / 4 Nights",
      price: "₹45,999",
      originalPrice: "₹65,999",
      image:"/assets/mt2.jpg",
      rating: 4.9,
      category: "International",
      inclusions: ["5-Star Hotel", "Breakfast", "Desert Safari", "City Tour", "Burj Khalifa"],
      discount: 30,
      description: "Experience luxury in the desert city with world-class shopping, iconic architecture, and thrilling desert adventures.",
      popular: true
    },
    {
      id: 5,
      title: "Singapore Family Fun",
      location: "Singapore",
      duration: "4 Days / 3 Nights",
      price: "₹38,999",
      originalPrice: "₹52,999",
      image:"/assets/mt3.jpg",
      rating: 4.8,
      category: "Family",
      inclusions: ["Hotel Stay", "Breakfast", "Universal Studios", "Sentosa Island", "City Tour"],
      discount: 26,
      description: "Perfect family destination with theme parks, gardens, and modern attractions for all ages.",
      popular: true
    },
    {
      id: 6,
      title: "Bali Honeymoon Special",
      location: "Bali",
      duration: "6 Days / 5 Nights",
      price: "₹42,999",
      originalPrice: "₹58,999",
      rating: 4.9,
      image:"/assets/mt5.jpg",
      category: "Honeymoon",
      inclusions: ["Villa Stay", "Breakfast", "Spa Treatment", "Romantic Dinner", "Island Tour"],
      discount: 27,
      description: "Romantic getaway with private villas, spa treatments, and stunning tropical landscapes.",
      popular: false
    },
    {
      id: 7,
      title: "Rajasthan Royal Tour",
      location: "Rajasthan",
      duration: "7 Days / 6 Nights",
      price: "₹22,999",
      originalPrice: "₹32,999",
      rating: 4.6,
      category: "Cultural",
      image:"/assets/mt4.jpg",
      inclusions: ["Heritage Hotels", "Breakfast", "Palace Tours", "Camel Safari", "Cultural Shows"],
      discount: 30,
      description: "Experience royal heritage with palace stays, desert safaris, and vibrant cultural performances.",
      popular: false
    },
    {
      id: 8,
      title: "Weekend Goa Special",
      location: "Goa",
      duration: "3 Days / 2 Nights",
      price: "₹8,999",
      originalPrice: "₹12,999",
      rating: 4.7,
      category: "Weekend",
      image:"/assets/mt6.jpg",
      inclusions: ["Beach Resort", "Breakfast", "Beach Activities", "Nightlife"],
      discount: 31,
      description: "Quick weekend escape to sunny beaches with perfect blend of relaxation and entertainment.",
      popular: false
    }
  ];