export const portfolioItems = [
  {
    id: 1,
    title: "Swiss Alps Luxury Retreat",
    category: "International Luxury",
    location: "Switzerland",
    duration: "7 Days",
    groupSize: "2-4 People",
    price: "Starting from $4,999",
    image: "https://images.unsplash.com/photo-1760900090912-5c2764433e75?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.9,
    featured: true,
    description: "Experience breathtaking beauty of Swiss Alps with luxury accommodations and personalized service."
  },
  {
    id: 2,
    title: "Dubai Corporate Excellence",
    category: "Corporate MICE",
    location: "Dubai, UAE",
    duration: "5 Days",
    groupSize: "20-50 People",
    price: "Custom Quote",
    image: "https://images.unsplash.com/photo-1728141144230-fd204de6922a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8RHViYWklMjBDb3Jwb3JhdGUlMjBFeGNlbGxlbmNlfGVufDB8fDB8fHww",
    rating: 4.8,
    featured: true,
    description: "Premium corporate event planning with world-class venues and exceptional service."
  },
  {
    id: 3,
    title: "Rajasthan Heritage Tour",
    category: "Cultural Luxury",
    location: "Rajasthan, India",
    duration: "10 Days",
    groupSize: "4-8 People",
    price: "Starting from $2,499",
    image: "https://images.unsplash.com/photo-1763910082102-2b74ffbfdfa7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fFJhamFzdGhhbiUyMEhlcml0YWdlJTIwVG91cnxlbnwwfHwwfHx8MA%3D%3D",
    rating: 4.9,
    featured: false,
    description: "Discover royal heritage of Rajasthan with palace stays and cultural experiences."
  },
  {
    id: 4,
    title: "Maldives Paradise Escape",
    category: "Honeymoon Special",
    location: "Maldives",
    duration: "6 Days",
    groupSize: "2 People",
    price: "Starting from $3,999",
    image: "https://media.istockphoto.com/id/1047631806/photo/young-adult-woman-relaxing-on-a-swing-in-a-tropical-paradise.webp?a=1&b=1&s=612x612&w=0&k=20&c=0SNqQ8uDXJ8c3raM8lNpN8OAdowhpIxj1eI2Qk_MECI=",
    rating: 5.0,
    featured: true,
    description: "Ultimate romantic getaway with overwater villas and pristine beaches."
  },
  {
    id: 5,
    title: "Tokyo Business & Leisure",
    category: "Corporate Travel",
    location: "Tokyo, Japan",
    duration: "8 Days",
    groupSize: "10-15 People",
    price: "Custom Quote",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2t5byUyMGNpdHl8ZW58MHx8fHwxNzY4OTk2MzY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    rating: 4.7,
    featured: false,
    description: "Perfect blend of business meetings and cultural exploration in modern Tokyo."
  },
  {
    id: 6,
    title: "Santorini Sunset Experience",
    category: "European Luxury",
    location: "Santorini, Greece",
    duration: "5 Days",
    groupSize: "2-6 People",
    price: "Starting from $2,999",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYW50b3Jpbml8ZW58MHx8fHwxNzY4OTk2MzY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    rating: 4.9,
    featured: false,
    description: "Romantic Greek island experience with stunning sunsets and luxury accommodations."
  },
  {
    id: 7,
    title: "Bali Spiritual Journey",
    category: "Cultural Luxury",
    location: "Bali, Indonesia",
    duration: "8 Days",
    groupSize: "2-6 People",
    price: "Starting from $1,999",
    image: "https://media.istockphoto.com/id/2135023427/photo/woman-traveler-with-backpack-enjoying-balinese-hindu-temple-entrance-female-tourist-during.webp?a=1&b=1&s=612x612&w=0&k=20&c=7lYHoMrZObd1AlrK66OxKuYnA1MHHqMtAN1r_n6ubsY=",
    rating: 4.8,
    featured: false,
    description: "Spiritual and cultural immersion in the island of gods with luxury wellness retreats."
  },
  {
    id: 8,
    title: "Paris Romantic Getaway",
    category: "European Luxury",
    location: "Paris, France",
    duration: "5 Days",
    groupSize: "2 People",
    price: "Starting from $3,499",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXJpc3xlbnwwfHx8fDE3Njg5OTYzNjh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    rating: 4.9,
    featured: true,
    description: "Experience the city of love with luxury accommodations and exclusive experiences."
  },
  {
    id: 9,
    title: "Singapore Corporate Summit",
    category: "Corporate MICE",
    location: "Singapore",
    duration: "4 Days",
    groupSize: "15-30 People",
    price: "Custom Quote",
    image: "https://plus.unsplash.com/premium_photo-1697730417971-437dc0b88fd4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8U2luZ2Fwb3JlJTIwQ29ycG9yYXRlJTIwU3VtbWl0fGVufDB8fDB8fHww",
    rating: 4.7,
    featured: false,
    description: "World-class corporate events in the heart of Asia's business hub."
  },
  {
    id: 10,
    title: "Kerala Backwaters Honeymoon",
    category: "Honeymoon Special",
    location: "Kerala, India",
    duration: "7 Days",
    groupSize: "2 People",
    price: "Starting from $1,799",
    image: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxrZXJhbGElMjBiYWNrd2F0ZXJ8ZW58MHx8fHwxNzY4OTk2MzY4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    rating: 4.8,
    featured: false,
    description: "Romantic houseboat experience in the serene backwaters of Kerala."
  }
];

export const tourCategories = ["All", "International Luxury", "Corporate MICE", "Cultural Luxury", "Honeymoon Special", "European Luxury", "Corporate Travel"];
